spring:
  data:
    redis:
      host: ${REDIS_URL:host.docker.internal}
      port: ${REDIS_PORT:6379}
    channels:
      calculations_channel: ${REDIS_CALCULATIONS_CHANNEL:calculations_channel}

currency-exchange:
  enabled: ${CURRENCY_EXCHANGE_ENABLED:false}
  api:
    url: ${CURRENCY_EXCHANGE_API_URL:https://api.exchangeratesapi.io/v1}
    access-key: ${CURRENCY_EXCHANGE_ACCESS_KEY:disabled}
    base: ${CURRENCY_EXCHANGE_BASE:EUR}
    connect-timeout: ${CURRENCY_EXCHANGE_CONNECT_TIMEOUT:PT3S}
    request-timeout: ${CURRENCY_EXCHANGE_REQUEST_TIMEOUT:PT10S}
    connection-retry-delay: ${CURRENCY_EXCHANGE_RETRY_DELAY:PT1S}
    connection-retry-max-delay: ${CURRENCY_EXCHANGE_RETRY_MAX_DELAY:PT10S}
    connection-retry-attempts: ${CURRENCY_EXCHANGE_RETRY_ATTEMPTS:3}
    connection-retry-jitter: ${CURRENCY_EXCHANGE_RETRY_JITTER:0.5}
    cache-ttl: ${CURRENCY_EXCHANGE_CACHE_TTL:PT13H}
    refresh-timeout: ${CURRENCY_EXCHANGE_REFRESH_TIMEOUT:PT2M}
  cron-expression: ${CURRENCY_EXCHANGE_CRON:0 0 */12 * * ?}

server:
  port: ${PAYMENT_SERVICE_PORT:8082}

logging:
  level:
    root: info
    liquibase: info
    org.hibernate.SQL: info
