spring:
  data:
    redis:
      host: ${REDIS_URL:host.docker.internal}
      port: ${REDIS_PORT:6379}
    channels:
      calculations_channel: ${REDIS_CALCULATIONS_CHANNEL:calculations_channel}

currency-exchange:
  api:
    url: https://api.exchangeratesapi.io/v1
    accessKey: 4dcf7f1ca62741ea341666f5de57f454
    base: EUR
    connectionRetrySeconds: 60
    connectionRetryAttempts: 5
  cron-expression: 0 0 */12 * * ?

server:
  port: ${PAYMENT_SERVICE_PORT:8082}

logging:
  level:
    root: info
    liquibase: info
    org.hibernate.SQL: info